<html>
<body>
<div align="center">
<h3>Prepared by Omar Mahmoud</h3>
    
<h1>Numpy</h1>

<h3>Note: This repository is for a personal Reference and study</h3>

<h3>Follow Me on - <a href="https://www.linkedin.com/in/omar-mahmoud-5bb616175/">LinkedIn</a>&nbsp; <a href="https://twitter.com/OmarMah25544092">Twitter</a>&nbsp; <a href="https://www.instagram.com/3amory99/">Instagram</a>&nbsp; <a href="https://www.facebook.com/Mora898/">Facebook</a></h3>
</div>

</div>
</body>
</html>

# NumPy 
- *stands for Numerical Python and it's a fundamental package for scientific computing in Python. NumPy provides Python with an extensive math library capable of performing numerical computations effectively and efficiently. `( Udacity Course def. )`*
- *Numpy is a Linear Algebra Library for Python,*
- *Numpy operations are so fast in vector and math operations.*
- *Numpy is used in Data Wrangling*
- *Is raleted to Mathematics, Highly optimized*
- *Has a large number of optimized built-in mathematical functions.*
- *Another great feature of NumPy is that it has multidimensional array data structures that can represent vectors and matrices.*
- *In general, one of best the third party libraries which facilitate Math in Python programming.*

**Vector = List**

**Matrix = compination of list (vectors)**

### Important features in Numpy
- **Numpy Array**
- **Built in Methods**
- **Reshaping**

In [3]:
# we can install it through writing
!pip install numpy
# or
conda install numpy

You should consider upgrading via the 'C:\ProgramData\Anaconda3\python.exe -m pip install --upgrade pip' command.


## Why we use NumPy ?

In [1]:
import time
import numpy as np

In [202]:
dir(np)

['ALLOW_THREADS',
 'AxisError',
 'BUFSIZE',
 'Bytes0',
 'CLIP',
 'ComplexWarning',
 'DataSource',
 'Datetime64',
 'ERR_CALL',
 'ERR_DEFAULT',
 'ERR_IGNORE',
 'ERR_LOG',
 'ERR_PRINT',
 'ERR_RAISE',
 'ERR_WARN',
 'FLOATING_POINT_SUPPORT',
 'FPE_DIVIDEBYZERO',
 'FPE_INVALID',
 'FPE_OVERFLOW',
 'FPE_UNDERFLOW',
 'False_',
 'Inf',
 'Infinity',
 'MAXDIMS',
 'MAY_SHARE_BOUNDS',
 'MAY_SHARE_EXACT',
 'MachAr',
 'ModuleDeprecationWarning',
 'NAN',
 'NINF',
 'NZERO',
 'NaN',
 'PINF',
 'PZERO',
 'RAISE',
 'RankWarning',
 'SHIFT_DIVIDEBYZERO',
 'SHIFT_INVALID',
 'SHIFT_OVERFLOW',
 'SHIFT_UNDERFLOW',
 'ScalarType',
 'Str0',
 'Tester',
 'TooHardError',
 'True_',
 'UFUNC_BUFSIZE_DEFAULT',
 'UFUNC_PYVALS_NAME',
 'Uint64',
 'VisibleDeprecationWarning',
 'WRAP',
 '_NoValue',
 '_UFUNC_API',
 '__NUMPY_SETUP__',
 '__all__',
 '__builtins__',
 '__cached__',
 '__config__',
 '__deprecated_attrs__',
 '__dir__',
 '__doc__',
 '__expired_functions__',
 '__file__',
 '__getattr__',
 '__git_revision__',
 '__loader__',

In [200]:
rand = np.random.random(1000000)

In [49]:
rand

array([0.17156856, 0.92016372, 0.47830308, ..., 0.51759585, 0.71366337,
       0.83267445])

In [57]:
# Case 1
start = time.time()
sum(rand) / len(rand)
fCase = time.time() - start
print(fCase)

0.10073161125183105


In [58]:
# Case 2
start = time.time()
np.mean(rand)
sCase = time.time() - start
print(sCase)

0.002989530563354492


In [60]:
sCase > fCase

False

In [63]:
difference = fCase - sCase
print(difference)

0.09774208068847656


**Numpy arrays essentially come in two flavors: vectors and matrices. Vectors are strictly 1-d arrays and matrices are 2-d (but you should note a matrix can still have only one row or one column).**

## Numpy Array Creation 

In [2]:
import numpy as np

# 1-D array   *Vector*
lista = [i for i in range(50)]
x = np.array(lista)

In [14]:
x

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33,
       34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49])

In [15]:
print(type(x))

<class 'numpy.ndarray'>


In [16]:
# 1-D array
x.shape

(50,)

In [17]:
# 2-D array   *Matrix*
x = np.array([[1,2,3],[4,5,6],[7,8,9], [10,11,12]])
x

array([[ 1,  2,  3],
       [ 4,  5,  6],
       [ 7,  8,  9],
       [10, 11, 12]])

In [19]:
# 2-D array
x.shape

(4, 3)

In [22]:
#Get memory address of an array object
x.data

In [25]:
# Convert Integer Array to FLOAT
x.astype(float)

array([[ 1.,  2.,  3.],
       [ 4.,  5.,  6.],
       [ 7.,  8.,  9.],
       [10., 11., 12.]])

**arange**

In [26]:
np.arange(0,10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [28]:
# arange(left, right, saperate)
np.arange(0,100,10)

array([ 0, 10, 20, 30, 40, 50, 60, 70, 80, 90])

In [62]:
# Generate numbers between 10 to 100 with a space of 10 in descending order
np.arange(100,0,-10)

array([100,  90,  80,  70,  60,  50,  40,  30,  20,  10])

In [68]:
# Generate array of Odd numbers
ar1 = np.arange(1,50)
ar1[ar1 % 2 == 1]

array([ 1,  3,  5,  7,  9, 11, 13, 15, 17, 19, 21, 23, 25, 27, 29, 31, 33,
       35, 37, 39, 41, 43, 45, 47, 49])

In [70]:
# Generate array of Even numbers
ar1 = np.arange(1,50)
ar1[ar1 % 2 == 0]

array([ 2,  4,  6,  8, 10, 12, 14, 16, 18, 20, 22, 24, 26, 28, 30, 32, 34,
       36, 38, 40, 42, 44, 46, 48])

**linspace**

In [154]:
# Generate evenly spaced 5 numbers between 0 to 100.

# (start, end, space) ======>> (end-start)/(space-1) = num >>> this is the number whice we add it to get the series
#                             0       0+25 =25     25+25=50        50+25=75        100
np.linspace(0,100,5)

array([  0.,  25.,  50.,  75., 100.])

In [155]:
np.linspace(0, 1, 10)

array([0.        , 0.11111111, 0.22222222, 0.33333333, 0.44444444,
       0.55555556, 0.66666667, 0.77777778, 0.88888889, 1.        ])

**repeat**

In [70]:
x = np.arange(0,10)
np.repeat(x,3)

array([0, 0, 0, 1, 1, 1, 2, 2, 2, 3, 3, 3, 4, 4, 4, 5, 5, 5, 6, 6, 6, 7,
       7, 7, 8, 8, 8, 9, 9, 9])

In [72]:
np.repeat(5,10)

array([5, 5, 5, 5, 5, 5, 5, 5, 5, 5])

In [76]:
# Repeat whole array twice
np.tile(x, 2)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [77]:
# Repeat whole array 3 times
np.tile(x, 3)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 0, 1,
       2, 3, 4, 5, 6, 7, 8, 9])

**full**


In [50]:
np.full(8,5)

array([5, 5, 5, 5, 5, 5, 5, 5])

**zeros**

In [51]:
Z = np.zeros(5)
Z

array([0., 0., 0., 0., 0.])

In [53]:
Z = np.zeros((3,3))
Z

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [54]:
Z = np.zeros((3,3,4))
Z

array([[[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]],

       [[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]],

       [[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]]])

**ones**

In [57]:
o = np.ones(3)
o

array([1., 1., 1.])

In [58]:
o = np.ones((3,3))
o

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [59]:
o = np.ones((3,3,4))
o

array([[[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]],

       [[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]],

       [[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]]])

**eye**

AA^-1 = I

In [239]:
# Create Identity Matrix (I)
np.eye(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

***Note : Normal distribution (mean=0 and variance=1)***

**random, rand**

Create an array of the given shape and populate it with random samples from a uniform distribution over [0,1].



In [94]:
np.random.random(5)

array([0.34686904, 0.03970041, 0.66436528, 0.23795828, 0.03419608])

np.random.rand(5)== np.random.random(5)

In [97]:
np.random.rand(5)

array([0.72761688, 0.06514073, 0.38474137, 0.34768356, 0.47178024])

In [102]:
# Generate a random Integer numbers
np.random.randint(0,10)

4

In [156]:
# Generate an array of Random Integer numbers
np.random.randint(0,100,5)

array([59, 26,  5, 71, 13])

In [157]:
np.random.rand(3, 3)


array([[0.21836729, 0.99392532, 0.57711101],
       [0.97103579, 0.42836491, 0.26860306],
       [0.51719037, 0.30959931, 0.72980664]])

**randint**

In [129]:
np.random.randint(10)

7

In [142]:
np.random.randint(0,50,4)

array([17, 36,  1,  3])

In [199]:
np.random.randint(0,100,(3,3))

array([[73, 32, 46],
       [96, 25, 83],
       [78, 36, 96]])

In [224]:
# Using random.seed we can generate same number of Random numbers
np.random.seed(123)
np.random.randint(0,100,10)

array([66, 92, 98, 17, 83, 57, 86, 97, 96, 47])

In [225]:
np.random.seed(101)
np.random.randint(0,100,10)

array([95, 11, 81, 70, 63, 87, 75,  9, 77, 40])

**randn**

In [161]:
#np.random.randn(number of array elements)
np.random.randn(5)

array([ 0.78819768,  0.23233462,  0.64302575, -0.24160585,  1.6016427 ])

In [226]:
np.random.randn(3,4)

array([[ 0.65111795, -0.31931804, -0.84807698,  0.60596535],
       [-2.01816824,  0.74012206,  0.52881349, -0.58900053],
       [ 0.18869531, -0.75887206, -0.93323722,  0.95505651]])

**uniform**

In [237]:
nums = np.random.uniform(0,100,size = (10))
nums

array([44.23681315, 87.75873246, 94.9264129 , 47.81674168, 46.11193423,
       63.7289031 , 32.46079964, 11.7578093 ,  5.11009964, 63.76586528])

Extract Integer part

In [233]:
np.floor(nums)

array([68., 52.,  4., 22., 57., 12., 50., 13.,  5., 17.])

In [238]:
np.trunc(nums)

array([44., 87., 94., 47., 46., 63., 32., 11.,  5., 63.])

#### Enumerate for Numpy Arrays

In [244]:
for i, j in np.ndenumerate(nums):
    print(i,j)

(0,) 44.236813151274475
(1,) 87.75873246276348
(2,) 94.9264128985194
(3,) 47.816741678956944
(4,) 46.11193422864347
(5,) 63.7289031017357
(6,) 32.4607996437537
(7,) 11.757809302799405
(8,) 5.110099639577459
(9,) 63.76586528178253


### Rank of an Array

In [3]:
# 1-D array
x = np.array([1, 2, 3])
x.ndim

1

In [10]:
# 2-D array
Y = np.array([[1,2,3],[4,5,6],[7,8,9], [10,11,12]])
Y.ndim

2

In [12]:
print(np.linalg.matrix_rank(Y))

2


In [13]:
# Get rang by linear algebra

out = np.array([[1,2,3],[4,-3,6],[7,8,0]])

print("\n Matrix (out)  ==>  \n", out)

print("\nRank of out ==> ", np.linalg.matrix_rank(out))


 Matrix (out)  ==>  
 [[ 1  2  3]
 [ 4 -3  6]
 [ 7  8  0]]

Rank of out ==>  3


In [3]:
Z.ndim

3

In [5]:
Z.dtype

dtype('float64')

In [7]:
Z.size

36

In [11]:
# return tuple (number of dimentions, size of array(row), size of array(column) )
Z.shape

(3, 3, 4)

In [12]:
Y = np.array([[1,2,3],[4,5,6],[7,8,9], [10,11,12]])
Y.shape

(4, 3)

In [13]:
Y.size

12

In [18]:
x = np.array(["Hello","Omar"])
print("Shape", x.shape)
print("Size", x.size)
print("Type", type(x))
print("DType", x.dtype)

Shape (2,)
Size 2
Type <class 'numpy.ndarray'>
DType <U5


In [19]:
# U5 == Unicode Strings

In [32]:
#Using a 1-D Array of Mixed Datatype
x = np.array([1,2,3,4.5,5.05])
x.dtype

dtype('float64')

In [35]:
# Bytes consumed by one element of an array object
x.itemsize

8

In [37]:
# 5x8 = 40 bytes
x.nbytes

40

In [23]:
#This called *Upcasting*

In [25]:
# We create a rank 1 ndarray that contains integers
x = np.array([1,2,3])

# We create a rank 1 ndarray that contains floats
y = np.array([1.0,2.0,3.0])

# We create a rank 1 ndarray that contains integers and floats
z = np.array([1, 2.5, 4])

# We print the dtype of each ndarray
print('The elements in x are of type:', x.dtype)
print('The elements in y are of type:', y.dtype)
print('The elements in z are of type:', z.dtype)

The elements in x are of type: int32
The elements in y are of type: float64
The elements in z are of type: float64


In [28]:
# We create a rank 1 ndarray of floats but set the dtype to int64
arr = np.array([1.5, 2.2, 3.7, 4.0, 5.9], dtype = np.int64)
print(arr)

[1 2 3 4 5]


In [4]:
# We create a rank 2 ndarray that only contains integers
Y = np.array([[1,2,3],[4,5,6],[7,8,9], [10,11,12]])

print('Y = \n', Y)

# We print information about Y
print('Y has dimensions:', Y.shape)
print('Y has a total of', Y.size, 'elements')
print('Y is an object of type:', type(Y))
print('The elements in Y are of type:', Y.dtype)

Y = 
 [[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]]
Y has dimensions: (4, 3)
Y has a total of 12 elements
Y is an object of type: <class 'numpy.ndarray'>
The elements in Y are of type: int32


### Operations on an Array
- sum
- cumsum
- max
- min
- argmax
- argmin
- mean
- median
- variance
- standard deviation
- percentiles
- amin
- sqrt
- exp
- log
- sin
- cos
- tan

In [3]:
arr1 = np.arange(1,11)
arr1

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [4]:
# Sum of all elements in an array
np.sum(arr1)

55

In [5]:
# Cumulative (Prefix) Sum : is the series of numbers which the current position value is the sum of all previous values
# https://www.youtube.com/watch?v=hqOqr6vFPp8
# always we can found the sum of the array in last element position
np.cumsum(arr1)

array([ 1,  3,  6, 10, 15, 21, 28, 36, 45, 55], dtype=int32)

In [6]:
np.max(arr1)

10

In [7]:
a = np.random.randint(1,100,(3,3))
a

array([[82,  8, 39],
       [21, 52, 36],
       [39, 75, 25]])

In [8]:
np.max(a)

82

In [9]:
a.max()

82

In [10]:
np.min(arr1)

1

In [11]:
np.min(a)

8

In [12]:
a.min()

8

argmax()  Find INDEX of Maximum number in an array

In [13]:
a.argmax()

0

In [14]:
np.argmax(a)

0

*argmin Find INDEX of Minimum number in an array*
- We usually use it in ML like prediction and classification ex. find the index of multiclassification prediction output

In [15]:
a.argmin()

1

In [16]:
np.argmin(a)

1

In [17]:
arr1.mean()

5.5

In [18]:
a.mean()

41.888888888888886

In [19]:
np.mean(a)

41.888888888888886

In [20]:
np.median(a)

39.0

In [21]:
np.median(arr1)

5.5

In [22]:
a.var()

525.4320987654321

In [25]:
a.std()

22.922305703515782

In [27]:
np.std(a)

22.922305703515782

In [29]:
arr1.std()

2.8722813232690143

In [31]:
np.std(arr1)

2.8722813232690143

In [37]:
np.percentile(a,70) # == Median

46.8

In [36]:
np.percentile(arr1,70)

7.3

In [40]:
# 20th & 70th percentile
np.percentile(a,[20,70])

array([23.4, 46.8])

In [41]:
np.percentile(arr1,[20,70])

array([2.8, 7.3])

In [47]:
# column wise mimimum value 
np.amin(a,axis= 0)

array([21,  8, 25])

In [173]:
# row wise mimimum value 
np.amin(a,axis= 1)

AxisError: axis 1 is out of bounds for array of dimension 1

In [182]:
x = np.arange(0,10)
x

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [184]:
z = np.random.randint(0,10,(3,3))
z

array([[7, 4, 2],
       [3, 9, 3],
       [9, 1, 2]])

In [179]:
np.power(x,2)

array([ 0,  1,  4,  9, 16, 25, 36, 49, 64, 81], dtype=int32)

In [186]:
np.power(z,2)

array([[49, 16,  4],
       [ 9, 81,  9],
       [81,  1,  4]], dtype=int32)

In [188]:
np.sqrt(x)

array([0.        , 1.        , 1.41421356, 1.73205081, 2.        ,
       2.23606798, 2.44948974, 2.64575131, 2.82842712, 3.        ])

In [190]:
np.sqrt(z)

array([[2.64575131, 2.        , 1.41421356],
       [1.73205081, 3.        , 1.73205081],
       [3.        , 1.        , 1.41421356]])

In [192]:
np.exp(x)

array([1.00000000e+00, 2.71828183e+00, 7.38905610e+00, 2.00855369e+01,
       5.45981500e+01, 1.48413159e+02, 4.03428793e+02, 1.09663316e+03,
       2.98095799e+03, 8.10308393e+03])

In [194]:
np.exp(y)

array([2.20264658e+04, 3.26901737e+06, 4.85165195e+08, 7.20048993e+10,
       1.00000000e+00, 1.00000000e+00, 1.00000000e+00, 1.00000000e+00,
       1.00000000e+00, 7.69478527e+23, 1.14200739e+26, 1.69488924e+28,
       2.51543867e+30, 3.73324200e+32, 5.54062238e+34, 8.22301271e+36,
       1.22040329e+39, 1.81123908e+41])

In [196]:
np.log(x)

<ipython-input-196-de666c833898>:1: RuntimeWarning: divide by zero encountered in log
  np.log(x)


array([      -inf, 0.        , 0.69314718, 1.09861229, 1.38629436,
       1.60943791, 1.79175947, 1.94591015, 2.07944154, 2.19722458])

In [203]:
np.exp(z)

array([[1.09663316e+03, 5.45981500e+01, 7.38905610e+00],
       [2.00855369e+01, 8.10308393e+03, 2.00855369e+01],
       [8.10308393e+03, 2.71828183e+00, 7.38905610e+00]])

In [208]:
arr = np.array([0,30,45,60,90,135,180,180,220,270,340])
arr

array([  0,  30,  45,  60,  90, 135, 180, 180, 220, 270, 340])

In [210]:
np.sin(arr)

array([ 0.        , -0.98803162,  0.85090352, -0.30481062,  0.89399666,
        0.08836869, -0.80115264, -0.80115264,  0.08839871, -0.17604595,
        0.65031074])

In [212]:
np.cos(arr)

array([ 1.        ,  0.15425145,  0.52532199, -0.95241298, -0.44807362,
       -0.99608784, -0.59846007, -0.59846007,  0.99608517,  0.98438195,
        0.75966831])

In [215]:
# cos(0) = 1
np.cos(arr[0])

1.0

In [216]:
np.tan(arr)

array([ 0.        , -6.4053312 ,  1.61977519,  0.32004039, -1.99520041,
       -0.08871576,  1.33869021,  1.33869021,  0.08874614, -0.17883906,
        0.85604563])

**shape && reshape**

Returns an array containing the same data with a new shape.

In [50]:
a.shape

(3, 3)

In [51]:
np.shape(a)

(3, 3)

In [56]:
a.reshape(9)

array([82,  8, 39, 21, 52, 36, 39, 75, 25])

In [71]:
a.reshape((1,9))

array([[82,  8, 39, 21, 52, 36, 39, 75, 25]])

In [72]:
a.reshape((9,1))

array([[82],
       [ 8],
       [39],
       [21],
       [52],
       [36],
       [39],
       [75],
       [25]])

In [74]:
a.reshape((9,1)).shape

(9, 1)

### Broadcasting
- **a technique in numpy used to make operations on different array sizes like multiply or sum a scaler to an array.**
- **It is very important in Ml**

In [77]:
x = np.arange(10,100,5)
x

array([10, 15, 20, 25, 30, 35, 40, 45, 50, 55, 60, 65, 70, 75, 80, 85, 90,
       95])

In [78]:
# All of numpy array
x[:]

array([10, 15, 20, 25, 30, 35, 40, 45, 50, 55, 60, 65, 70, 75, 80, 85, 90,
       95])

In [79]:
x[0:5]

array([10, 15, 20, 25, 30])

In [81]:
x[-1]

95

In [82]:
x[0:3]

array([10, 15, 20])

In [83]:
x[3:8]

array([25, 30, 35, 40, 45])

In [84]:
x[3:]

array([25, 30, 35, 40, 45, 50, 55, 60, 65, 70, 75, 80, 85, 90, 95])

In [86]:
x[:5]

array([10, 15, 20, 25, 30])

In [87]:
x[0:5] = 0

In [89]:
x

array([ 0,  0,  0,  0,  0, 35, 40, 45, 50, 55, 60, 65, 70, 75, 80, 85, 90,
       95])

In [218]:
x = np.arange(10,100,5)
x

array([10, 15, 20, 25, 30, 35, 40, 45, 50, 55, 60, 65, 70, 75, 80, 85, 90,
       95])

In [219]:
y = x[4:9]
y

array([30, 35, 40, 45, 50])

In [220]:
y[:] = -1
y

array([-1, -1, -1, -1, -1])

In [221]:
# It's not a copy, but it's the same array in the memory, this avoids memory problems
x

array([10, 15, 20, 25, -1, -1, -1, -1, -1, 55, 60, 65, 70, 75, 80, 85, 90,
       95])

*We can realize now that change also occur in the original array (x)*

In [222]:
x = np.arange(10,100,5)
x

array([10, 15, 20, 25, 30, 35, 40, 45, 50, 55, 60, 65, 70, 75, 80, 85, 90,
       95])

In [223]:
y = x.copy()
y

array([10, 15, 20, 25, 30, 35, 40, 45, 50, 55, 60, 65, 70, 75, 80, 85, 90,
       95])

In [224]:
y[4:9] = 0

In [225]:
y

array([10, 15, 20, 25,  0,  0,  0,  0,  0, 55, 60, 65, 70, 75, 80, 85, 90,
       95])

In [226]:
x

array([10, 15, 20, 25, 30, 35, 40, 45, 50, 55, 60, 65, 70, 75, 80, 85, 90,
       95])

**Fancy Indexing**

Fancy indexing allows you to select entire rows or columns out of order,to show this, let's quickly build out a numpy array:

In [229]:
#Set up matrix
arr = np.random.randint(1, 100, (10,10))
arr

array([[79, 55,  9, 95, 23, 10, 91, 67, 40, 35],
       [69, 60, 98, 70, 74, 45, 28, 94,  3, 79],
       [58, 19, 43, 83, 90, 18, 60,  5, 85, 91],
       [52, 12, 24, 84, 87, 34,  4, 19,  3, 54],
       [29, 15, 66, 87, 25, 15, 48, 83, 22, 15],
       [22, 92,  7, 76, 60, 59, 65, 38, 40, 48],
       [38, 40, 98, 66, 98, 78, 36, 48, 43, 82],
       [95, 27,  9, 83, 10, 12, 45, 51,  2, 72],
       [69, 38, 43, 71, 69, 87,  8, 64, 39, 29],
       [22, 52, 66, 57, 18, 38, 90, 36, 60, 74]])

In [231]:
arr[[2,4,6]]

array([[58, 19, 43, 83, 90, 18, 60,  5, 85, 91],
       [29, 15, 66, 87, 25, 15, 48, 83, 22, 15],
       [38, 40, 98, 66, 98, 78, 36, 48, 43, 82]])

In [235]:
arr[[2,4,6], 2:5]

array([[43, 83, 90],
       [66, 87, 25],
       [98, 66, 98]])

### Arithmetic

In [158]:
a = np.arange(0,10)
a

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [159]:
a+5

array([ 5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

In [160]:
a-5

array([-5, -4, -3, -2, -1,  0,  1,  2,  3,  4])

In [161]:
a*5

array([ 0,  5, 10, 15, 20, 25, 30, 35, 40, 45])

In [162]:
a/5

array([0. , 0.2, 0.4, 0.6, 0.8, 1. , 1.2, 1.4, 1.6, 1.8])

In [165]:
a//5

array([0, 0, 0, 0, 0, 1, 1, 1, 1, 1], dtype=int32)

In [166]:
a**2

array([ 0,  1,  4,  9, 16, 25, 36, 49, 64, 81], dtype=int32)

In [164]:
a/a

<ipython-input-164-18210b5178b0>:1: RuntimeWarning: invalid value encountered in true_divide
  a/a


array([nan,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.])

In [167]:
a*a

array([ 0,  1,  4,  9, 16, 25, 36, 49, 64, 81])

In [169]:
a > 5

array([False, False, False, False, False, False,  True,  True,  True,
        True])

In [172]:
a != 0 

array([False,  True,  True,  True,  True,  True,  True,  True,  True,
        True])

### Replace elements in array

In [114]:
x = np.arange(1,101)
x

array([  1,   2,   3,   4,   5,   6,   7,   8,   9,  10,  11,  12,  13,
        14,  15,  16,  17,  18,  19,  20,  21,  22,  23,  24,  25,  26,
        27,  28,  29,  30,  31,  32,  33,  34,  35,  36,  37,  38,  39,
        40,  41,  42,  43,  44,  45,  46,  47,  48,  49,  50,  51,  52,
        53,  54,  55,  56,  57,  58,  59,  60,  61,  62,  63,  64,  65,
        66,  67,  68,  69,  70,  71,  72,  73,  74,  75,  76,  77,  78,
        79,  80,  81,  82,  83,  84,  85,  86,  87,  88,  89,  90,  91,
        92,  93,  94,  95,  96,  97,  98,  99, 100])

In [115]:
# Replace EVEN numbers with ZERO
edit = np.where(x % 2 ==0, 0, x)
edit

array([ 1,  0,  3,  0,  5,  0,  7,  0,  9,  0, 11,  0, 13,  0, 15,  0, 17,
        0, 19,  0, 21,  0, 23,  0, 25,  0, 27,  0, 29,  0, 31,  0, 33,  0,
       35,  0, 37,  0, 39,  0, 41,  0, 43,  0, 45,  0, 47,  0, 49,  0, 51,
        0, 53,  0, 55,  0, 57,  0, 59,  0, 61,  0, 63,  0, 65,  0, 67,  0,
       69,  0, 71,  0, 73,  0, 75,  0, 77,  0, 79,  0, 81,  0, 83,  0, 85,
        0, 87,  0, 89,  0, 91,  0, 93,  0, 95,  0, 97,  0, 99,  0])

In [116]:
# Replace ODD numbers with ZERO
edit = np.where(x % 2 !=0, 0, x)
edit

array([  0,   2,   0,   4,   0,   6,   0,   8,   0,  10,   0,  12,   0,
        14,   0,  16,   0,  18,   0,  20,   0,  22,   0,  24,   0,  26,
         0,  28,   0,  30,   0,  32,   0,  34,   0,  36,   0,  38,   0,
        40,   0,  42,   0,  44,   0,  46,   0,  48,   0,  50,   0,  52,
         0,  54,   0,  56,   0,  58,   0,  60,   0,  62,   0,  64,   0,
        66,   0,  68,   0,  70,   0,  72,   0,  74,   0,  76,   0,  78,
         0,  80,   0,  82,   0,  84,   0,  86,   0,  88,   0,  90,   0,
        92,   0,  94,   0,  96,   0,  98,   0, 100])

*Replace values at INDEX loc 2,4,6 with 8,8,8*

In [2]:
x = np.arange(0,10)
x

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [3]:
np.put(x,[2,4,6],[100,100,100])

In [5]:
x

array([  0,   1, 100,   3, 100,   5, 100,   7,   8,   9])

### Missing Values in an array

In [36]:
x = np.array([2,4,6,np.nan,10,12,np.nan,np.nan,18,20,np.nan])
x

array([ 2.,  4.,  6., nan, 10., 12., nan, nan, 18., 20., nan])

In [37]:
# Search for missing values and return as a boolean array
np.isnan(x)

array([False, False, False,  True, False, False,  True,  True, False,
       False,  True])

In [40]:
# Index of missing values in an array
np.where(np.isnan(x))

(array([ 3,  6,  7, 10], dtype=int64),)

In [41]:
c = x.copy()

In [46]:
x[np.isnan(x)] = 100
x

array([  2.,   4.,   6., 100.,  10.,  12., 100., 100.,  18.,  20., 100.])

In [45]:
# Replace all missing values with 99
c[np.isnan(c)] = 99
c

array([ 2.,  4.,  6., 99., 10., 12., 99., 99., 18., 20., 99.])

In [59]:
# Check if array has any NULL value
np.isnan(x).any() 

False

In [61]:
ex = np.array([[1,2,np.nan,4] , [np.nan,6,7,8] , [10 , np.nan , 12 ,13] , [14,15,16,17]])
np.isnan(ex).any()

True

In [62]:
# Check if all array has any NULL values
np.isnan(c).all() 

False

In [63]:
np.isnan(ex).all() 

False

In [51]:
arr = np.array([[1,2,np.nan,4] , [np.nan,6,7,8] , [10 , np.nan , 12 ,13] , [14,15,16,17]])
arr

array([[ 1.,  2., nan,  4.],
       [nan,  6.,  7.,  8.],
       [10., nan, 12., 13.],
       [14., 15., 16., 17.]])

In [53]:
arr.shape

(4, 4)

In [65]:
# Search for missing values and return as a boolean array
np.isnan(arr)

array([[False, False,  True, False],
       [ True, False, False, False],
       [False,  True, False, False],
       [False, False, False, False]])

In [57]:
np.isnan(arr).any()

True

In [66]:
np.where(np.isnan(arr))

(array([0, 1, 2], dtype=int64), array([2, 0, 1], dtype=int64))

### Combine and Split data
- hstack --> Horizontally
- vstack --> Vertically
- concatenate
- hsplit
- vsplit

In [74]:
a = np.random.randint(0,20,(3,3))
a

array([[ 6, 19,  2],
       [18,  9, 19],
       [ 0,  8, 11]])

In [75]:
b = np.random.randint(0,20,(3,3))
b

array([[19, 12, 16],
       [15, 13,  3],
       [11, 10,  8]])

In [76]:
np.hstack([a,b])

array([[ 6, 19,  2, 19, 12, 16],
       [18,  9, 19, 15, 13,  3],
       [ 0,  8, 11, 11, 10,  8]])

In [77]:
c = np.zeros(20).reshape(2,-1)
d = np.repeat(1, 20).reshape(2,-1)
c

array([[0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.]])

In [79]:
d

array([[1, 1, 1, 1, 1, 1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1, 1, 1, 1, 1, 1]])

In [81]:
np.hstack([c,d])

array([[0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 1., 1., 1., 1., 1., 1.,
        1., 1., 1., 1.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 1., 1., 1., 1., 1., 1.,
        1., 1., 1., 1.]])

In [83]:
np.vstack([a,b])

array([[ 6, 19,  2],
       [18,  9, 19],
       [ 0,  8, 11],
       [19, 12, 16],
       [15, 13,  3],
       [11, 10,  8]])

In [86]:
np.vstack([c,d])

array([[0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.]])

In [93]:
# hstack & vstack

arr1 = np.array([[7,13,14],[18,10,17],[11,12,19]])
arr2= np.array([16,6,1])
arr3= np.array([[5,8,4,3]])

np.hstack((np.vstack((arr1,arr2)),np.transpose(arr3)))

array([[ 7, 13, 14,  5],
       [18, 10, 17,  8],
       [11, 12, 19,  4],
       [16,  6,  1,  3]])

In [94]:
np.concatenate([a,b],axis = 0)

array([[ 6, 19,  2],
       [18,  9, 19],
       [ 0,  8, 11],
       [19, 12, 16],
       [15, 13,  3],
       [11, 10,  8]])

In [96]:
collection = np.concatenate([a,b],axis = 1)
collection

array([[ 6, 19,  2, 19, 12, 16],
       [18,  9, 19, 15, 13,  3],
       [ 0,  8, 11, 11, 10,  8]])

In [99]:
left, right = np.hsplit(collection,2)

In [100]:
left

array([[ 6, 19,  2],
       [18,  9, 19],
       [ 0,  8, 11]])

In [102]:
right

array([[19, 12, 16],
       [15, 13,  3],
       [11, 10,  8]])

In [105]:
q1,median,q2 = np.hsplit(collection,3)

In [107]:
q1

array([[ 6, 19],
       [18,  9],
       [ 0,  8]])

In [109]:
median

array([[ 2, 19],
       [19, 15],
       [11, 11]])

In [115]:
q2

array([[12, 16],
       [13,  3],
       [10,  8]])

In [118]:
collection = np.concatenate([a,b],axis = 0)
collection

array([[ 6, 19,  2],
       [18,  9, 19],
       [ 0,  8, 11],
       [19, 12, 16],
       [15, 13,  3],
       [11, 10,  8]])

In [120]:
up, down = np.vsplit(collection,2)

In [121]:
up

array([[ 6, 19,  2],
       [18,  9, 19],
       [ 0,  8, 11]])

In [123]:
down

array([[19, 12, 16],
       [15, 13,  3],
       [11, 10,  8]])

In [125]:
up, median, down = np.vsplit(collection,3)

In [127]:
up

array([[ 6, 19,  2],
       [18,  9, 19]])

In [128]:
median

array([[ 0,  8, 11],
       [19, 12, 16]])

In [130]:
down

array([[15, 13,  3],
       [11, 10,  8]])

### Common items between two Numpy Arrays  ` (intersection)`

In [135]:
a1 = np.array([10,20,30,40,50,60])
a2 = np.array([12,20,33,40,55,60])

In [137]:
np.intersect1d(a1,a2)

array([20, 40, 60])

### Remove Common Elements, remove intersection

In [144]:
# Remove common elements of a1 & a2 array from a1
np.setdiff1d(a1,a2)

array([10, 30, 50])

In [146]:
# Remove common elements of a1 & a2 array from a2
np.setdiff1d(a2,a1)

array([12, 33, 55])

### Array with Conditions

In [167]:
x =  np.array([3,4,5,6,7,8,9])
y =  np.array([1,4,2,11,7,5,9])

In [168]:
# returns the indices of elements in an input array where the given condition is satisfied.
res = np.where(x == y)
res

(array([1, 4, 6], dtype=int64),)

In [164]:
# if we want to get these indices values
x[res]

array([4, 7, 9])

In [170]:
x[np.where(x == y)]

array([4, 7, 9])

In [171]:
x = np.arange(0,100)
x

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33,
       34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50,
       51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67,
       68, 69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81, 82, 83, 84,
       85, 86, 87, 88, 89, 90, 91, 92, 93, 94, 95, 96, 97, 98, 99])

In [174]:
# Return all numbers betweeen 10 & 30
x[np.where ((x>10) & (x<30))]

array([11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27,
       28, 29])

In [175]:
# Return all numbers betweeen 10 & 30 OR numbers divisible by 10
x[np.where(((x >10) & (x<30)) | (x % 10 == 0)) ]


array([ 0, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25,
       26, 27, 28, 29, 30, 40, 50, 60, 70, 80, 90])

### Check for elements in an Array using `isin()`

In [20]:
x = np.arange(100,1000,100)
x

array([100, 200, 300, 400, 500, 600, 700, 800, 900])

In [21]:
np.isin(x,[200,5])

array([False,  True, False, False, False, False, False, False, False])

In [22]:
x[np.isin(x,[200,5])]

array([200])

In [23]:
x[np.isin(x, 50)]

array([], dtype=int32)

In [28]:
# It's index
np.where(np.isin(x,[500]))

(array([4], dtype=int64),)

In [29]:
# Display the matching values
x[np.isin(x, [100,700])]

array([100, 700])

### Reverse Array


In [41]:
x = np.arange(10,20)
x

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19])

In [42]:
#Reverse the array
x[::-1]

array([19, 18, 17, 16, 15, 14, 13, 12, 11, 10])

In [43]:
x

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19])

In [49]:
# Another way
c = list(x)
c.reverse()

In [50]:
c

[19, 18, 17, 16, 15, 14, 13, 12, 11, 10]

In [53]:
c = np.array(c)
c

array([19, 18, 17, 16, 15, 14, 13, 12, 11, 10])

In [55]:
a = np.array([[3,2,8,1] , [70,50,10,67] , [45,25,75,15] , [12,9,77,4]])
a

array([[ 3,  2,  8,  1],
       [70, 50, 10, 67],
       [45, 25, 75, 15],
       [12,  9, 77,  4]])

In [65]:
# Reverse ROW positions
a[::-1,:]

array([[12,  9, 77,  4],
       [45, 25, 75, 15],
       [70, 50, 10, 67],
       [ 3,  2,  8,  1]])

In [67]:
# Reverse ROW positions
a[:,::-1]

array([[ 1,  8,  2,  3],
       [67, 10, 50, 70],
       [15, 75, 25, 45],
       [ 4, 77,  9, 12]])

In [69]:
# Reverse both ROW & COLUMN positions
a[::-1,::-1]

array([[ 4, 77,  9, 12],
       [15, 75, 25, 45],
       [67, 10, 50, 70],
       [ 1,  8,  2,  3]])

### Sorting Numpy Array

In [81]:
x = np.array([10,5,2,22,12,5,5,92,17,33])


In [85]:
x.sort()
x

array([ 2,  5,  5,  5, 10, 12, 17, 22, 33, 92])

In [86]:
np.sort(x)

array([ 2,  5,  5,  5, 10, 12, 17, 22, 33, 92])

Now note that Numpy sort function does not remove duplication like python sort list

In [96]:
a = np.array([[3,2,8,1] , [70,50,10,67] , [45,25,75,15]])
a

array([[ 3,  2,  8,  1],
       [70, 50, 10, 67],
       [45, 25, 75, 15]])

In [84]:
# sort all row  >> along rows
a.sort()
a

array([[ 1,  2,  3,  8],
       [10, 50, 67, 70],
       [15, 25, 45, 75]])

In [90]:
# sort all column  >> along column
np.sort(a,axis = 0)

array([[ 3,  2,  8,  1],
       [45, 25, 10, 15],
       [70, 50, 75, 67]])

In [92]:
# sort all row  >> along rows
np.sort(a,axis = 1)

array([[ 1,  2,  3,  8],
       [10, 50, 67, 70],
       [15, 25, 45, 75]])

In [97]:
# Sort in descending order
b = np.sort(a)
# we make reverse
b[::-1]
b

array([[ 1,  2,  3,  8],
       [10, 50, 67, 70],
       [15, 25, 45, 75]])

## That's great keep on ✨